Repository charmbracelet/glow, pull requests merged in 2020-10, with the labels that each got.

#167 Don't handle filenames with a colon in it as http(s) url
  main.go
Labels: bug

#189 Fix typo in README.md
  README.md
Labels: documentation

#194 Point out the 'glow config' command in README
  README.md
Labels: documentation

#186 Now in Scoop!
  README.md
Labels: documentation

#199 Ignore YAML frontmatter
  main.go
  ui/ui.go
  utils/utils.go
Labels: enhancement
