Repository charmbracelet/glow, pull requests merged in 2020-01, with the labels that each got.

#125 feat: support multiple files
  main.go
Labels: enhancement

#128 Enable ANSI for Windows consoles
  console_windows.go
  go.mod
Labels: bug

#132 Now in Homebrew!
  README.md
Labels: documentation
